In [145]:
#LETs do a data preprocessing process.

import numpy as np
# X = (hours sleeping, hours studying), y = Score on test
X = np.array(([12,1],[10,3],[8,5], [5,8], [3,10]), dtype=float)
y = np.array(([66],[70],[75], [82], [93]), dtype=float)

In [146]:
# Lets use simple method to scale the value of this neural network
y=y/100

In [147]:
X=X/(np.amax(X,axis=0))

In [148]:
# We have scaled data in X and y lets 

In [149]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.yHat = self.forward(X)
        J = 0.5*sum((y-self.yHat)**2)
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)  
        
        return dJdW1, dJdW2


In [150]:
NN=Neural_Network()

In [151]:
cost1=NN.costFunction(X,y)
cost1

array([0.05032583])

In [152]:
dJdW1,djdW2=NN.costFunctionPrime(X,y)

In [153]:
scaler=3
NN.W1=NN.W1+scaler*dJdW1
NN.W2=NN.W2+scaler*djdW2
cost=NN.costFunction(X,y)


In [154]:
print(cost)

[0.08425644]


In [155]:
scalar=3
NN.W1=NN.W1-scalar*dJdW1
NN.W2=NN.W2-scalar*djdW2
cost2=NN.costFunction(X,y)

In [156]:
cost2

array([0.05032583])

In [157]:
scalar=1
NN.W1=NN.W1-scalar*dJdW1
NN.W2=NN.W2-scalar*djdW2
cost2=NN.costFunction(X,y)

In [158]:
cost2

array([0.04291376])

In [159]:
yhat=NN.forward(X)

In [160]:
yhat[2]

array([0.70540209])

In [161]:
y[2]

array([0.75])

In [166]:
z=NN.forward([7,6])

In [167]:
z[0]

0.8102988521521597